apiVersion: v1
kind: Secret
metadata:
  name: aurcc-secrets
  namespace: default
type: Opaque
data:
  jwt-secret: REPLACE_WITH_BASE64_JWT_SECRET
  aws-access-key-id: REPLACE_WITH_BASE64_AWS_ACCESS_KEY_ID
  aws-secret-access-key: REPLACE_WITH_BASE64_AWS_SECRET_ACCESS_KEY
